apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virt-daemon
  namespace: virtink-system
spec:
  selector:
    matchLabels:
      name: virt-daemon
  template:
    metadata:
      labels:
        name: virt-daemon
    spec:
      serviceAccountName: virt-daemon
      hostPID: true
      containers:
        - name: virt-daemon
          image: virt-daemon
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - --zap-time-encoding=iso8601
          volumeMounts:
            - name: kubelet-pods
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: cert
              mountPath: /var/lib/virtink/daemon/cert
              readOnly: true
            - name: device-plugins
              mountPath: /var/lib/kubelet/device-plugins
            - name: devices
              mountPath: /dev
              mountPropagation: HostToContainer
            - name: virtink
              mountPath: /var/run/virtink
      volumes:
        - name: kubelet-pods
          hostPath:
            path: /var/lib/kubelet/pods
        - name: cert
          secret:
            secretName: virt-daemon-cert
            defaultMode: 420
        - name: device-plugins
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: devices
          hostPath:
            path: /dev
        - name: virtink
          hostPath:
            path: /var/run/virtink
